
import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/context/AuthContext";
import { useIsMobile } from "@/hooks/use-mobile";
import { cn } from "@/lib/utils";
import MysteryChat from "@/components/MysteryChat";
import { ArrowRight } from "lucide-react";
import { Message } from "@/components/types";
import { Conversation } from "@/interfaces/mystery";

const MysteryChatPage = () => {
  const [conversation, setConversation] = useState<Conversation | null>(null);
  const [loading, setLoading] = useState(true);
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoadingHistory, setIsLoadingHistory] = useState(false);
  const { id } = useParams();
  const navigate = useNavigate();
  const { isAuthenticated, user } = useAuth();
  const isMobile = useIsMobile();

  useEffect(() => {
    if (!isAuthenticated || !user) {
      navigate("/sign-in");
      return;
    }

    if (id) {
      loadConversation(id);
    }
  }, [id, isAuthenticated, user]);

  const loadConversation = async (conversationId: string) => {
    try {
      setLoading(true);
      setIsLoadingHistory(true);
      
      const { data, error } = await supabase
        .from("conversations")
        .select("*")
        .eq("id", conversationId)
        .eq("user_id", user?.id)
        .single();

      if (error) {
        console.error("Error loading conversation:", error);
        toast.error("Failed to load conversation");
        navigate("/");
        return;
      }

      setConversation(data);
      
      // Load messages if they exist
      if (data.messages && Array.isArray(data.messages)) {
        const formattedMessages: Message[] = data.messages.map((msg: any, index: number) => ({
          id: msg.id || index.toString(),
          content: msg.content || '',
          is_ai: msg.is_ai || msg.role === 'assistant',
          timestamp: msg.timestamp ? new Date(msg.timestamp) : new Date(),
          isAutoGenerated: msg.isAutoGenerated || false
        }));
        setMessages(formattedMessages);
      }
    } catch (error) {
      console.error("Error:", error);
      toast.error("Failed to load conversation");
      navigate("/");
    } finally {
      setLoading(false);
      setIsLoadingHistory(false);
    }
  };

  const handleSaveMessage = async (message: Message) => {
    if (!conversation) return;

    try {
      const updatedMessages = [...messages, message];
      setMessages(updatedMessages);

      // Update the conversation with the new message
      const { error } = await supabase
        .from("conversations")
        .update({
          messages: updatedMessages.map(msg => ({
            id: msg.id,
            content: msg.content,
            is_ai: msg.is_ai,
            timestamp: msg.timestamp.toISOString(),
            isAutoGenerated: msg.isAutoGenerated
          })),
          updated_at: new Date().toISOString()
        })
        .eq("id", conversation.id);

      if (error) {
        console.error("Error saving message:", error);
        toast.error("Failed to save message");
      }
    } catch (error) {
      console.error("Error saving message:", error);
      toast.error("Failed to save message");
    }
  };

  const handleGenerateFinal = async (chatMessages: Message[]) => {
    if (!conversation) return;

    try {
      // Mark conversation as completed
      const { error } = await supabase
        .from("conversations")
        .update({
          is_completed: true,
          updated_at: new Date().toISOString()
        })
        .eq("id", conversation.id);

      if (error) {
        console.error("Error updating conversation:", error);
        toast.error("Failed to finalize mystery");
        return;
      }

      toast.success("Mystery finalized! You can now preview it.");
      navigate(`/mystery/preview/${id}`);
    } catch (error) {
      console.error("Error finalizing mystery:", error);
      toast.error("Failed to finalize mystery");
    }
  };

  const handleGoToPreview = () => {
    navigate(`/mystery/preview/${id}`);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 flex items-center justify-center">
          <div className="h-8 w-8 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
        </main>
        <Footer />
      </div>
    );
  }

  if (!conversation) {
    return (
      <div className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <h1 className="text-2xl font-bold mb-2">Conversation not found</h1>
            <p className="text-muted-foreground mb-4">The conversation you're looking for doesn't exist.</p>
            <Button onClick={() => navigate("/")}>Go Home</Button>
          </div>
        </main>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className={cn("flex-1", isMobile ? "py-4 px-2" : "py-12 px-4")}>
        <div className={cn("container mx-auto", isMobile ? "max-w-full" : "max-w-6xl")}>
          <div className={cn("mb-8", isMobile && "mb-4")}>
            <h1 className={cn("text-3xl font-bold mb-2", isMobile && "text-2xl mb-1")}>
              Creating Your Mystery
            </h1>
            <p className="text-muted-foreground">
              Chat with our AI to refine and perfect your murder mystery
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
            <div className="lg:col-span-3">
              <Card>
                <CardContent className="p-0">
                  <MysteryChat
                    initialTheme={conversation.mystery_data?.theme}
                    initialPlayerCount={conversation.mystery_data?.playerCount}
                    initialHasAccomplice={conversation.mystery_data?.hasAccomplice}
                    initialScriptType={conversation.mystery_data?.scriptType}
                    initialAdditionalDetails={conversation.mystery_data?.additionalDetails}
                    savedMysteryId={conversation.id}
                    onSave={handleSaveMessage}
                    onGenerateFinal={handleGenerateFinal}
                    initialMessages={messages}
                    isLoadingHistory={isLoadingHistory}
                    skipForm={true}
                    needsInitialAIResponse={messages.length === 1 && !messages[0].is_ai}
                  />
                </CardContent>
              </Card>
            </div>
            
            <div className="lg:col-span-1">
              <Card>
                <CardContent className="p-6">
                  <h3 className="font-semibold mb-4">Next Steps</h3>
                  <p className="text-sm text-muted-foreground mb-4">
                    Once you're happy with your mystery concept, you can preview the full package and make your purchase.
                  </p>
                  <Button 
                    onClick={handleGoToPreview}
                    className="w-full"
                    variant="outline"
                  >
                    Go to Preview
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>

          <div className={cn("mt-8 flex justify-center gap-4", isMobile && "mt-4")}>
            <Button
              variant="outline"
              onClick={() => navigate("/")}
              size={isMobile ? "sm" : "default"}
            >
              Back to Dashboard
            </Button>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default MysteryChatPage;
