import { useState, useEffect } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import Header from "@/components/Header";
import { supabase } from "@/lib/supabase";
import MysteryChat from "@/components/MysteryChat";
import { useAuth } from "@/context/AuthContext";
import { useIsMobile } from "@/hooks/use-mobile";
import { cn } from "@/lib/utils";
import { Message } from "@/components/types";
import { Loader2, Zap } from "lucide-react";

const MysteryChatPage = () => {
    const [messages, setMessages] = useState<Message[]>([]);
    const [conversationData, setConversationData] = useState<any>(null);
    const [isLoadingHistory, setIsLoadingHistory] = useState(true);
    const navigate = useNavigate();
    const { id } = useParams();
    const [searchParams] = useSearchParams();
    const isInitial = searchParams.get('initial') === 'true';
    const { isAuthenticated, user } = useAuth();
    const isMobile = useIsMobile();

    useEffect(() => {
        if (id && isAuthenticated) {
            loadConversationData();
        }
    }, [id, isAuthenticated]);

    const loadConversationData = async () => {
        try {
            setIsLoadingHistory(true);
            
            const { data, error } = await supabase
                .from("conversations")
                .select("*, messages(*)")
                .eq("id", id)
                .single();

            if (error) {
                console.error("Error loading conversation:", error);
                toast.error("Failed to load conversation");
                return;
            }

            if (data) {
                setConversationData(data);
                
                // Load messages and sort by timestamp
                const formattedMessages = (data.messages || []).map((msg: any) => ({
                    id: msg.id,
                    content: msg.content,
                    is_ai: msg.role === "assistant",
                    timestamp: new Date(msg.created_at),
                    isAutoGenerated: false
                }));
                
                formattedMessages.sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());
                setMessages(formattedMessages);
            }
        } catch (error) {
            console.error("Error:", error);
            toast.error("Failed to load conversation");
        } finally {
            setIsLoadingHistory(false);
        }
    };

    const handleSaveMessage = async (message: Message) => {
        if (!id) return;
        
        try {
            await supabase.from("messages").insert({
                conversation_id: id,
                content: message.content,
                role: message.is_ai ? "assistant" : "user",
                is_ai: message.is_ai
            });

            // Update local messages state to keep button state in sync
            setMessages(prev => {
                const exists = prev.some(msg => msg.id === message.id);
                if (exists) {
                    return prev;
                }
                return [...prev, message].sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());
            });
        } catch (error) {
            console.error("Error saving message:", error);
            toast.error("Failed to save message");
        }
    };

    const handleGenerateFullMystery = () => {
        navigate(`/mystery/purchase/${id}`);
    };

    // Check if AI has provided at least one response
    const hasAIResponse = messages.some(msg => msg.is_ai);

    if (isLoadingHistory) {
        return (
            <div className="min-h-screen flex flex-col">
                <Header />
                <main className="flex-1 flex items-center justify-center">
                    <div className="text-center px-4">
                        <Loader2 className="h-6 w-6 sm:h-8 sm:w-8 animate-spin mx-auto mb-4" />
                        <p className="text-sm sm:text-base text-muted-foreground">Loading conversation...</p>
                    </div>
                </main>
            </div>
        );
    }

    return (
        <div className="min-h-screen flex flex-col bg-[#F7F3E9]">
            <Header />
            <main className={cn(
                "flex-1 pb-32", // Add padding at the bottom for fixed elements
                isMobile ? "pt-2 px-3" : "pt-4 px-4"
            )}>
                <div className={cn(
                    "mx-auto",
                    isMobile ? "max-w-full" : "max-w-4xl"
                )}>
                    {/* Chat Interface - Full Page Scrolling */}
                    <MysteryChat
                        initialTheme={conversationData?.mystery_data?.theme || ""}
                        initialPlayerCount={conversationData?.mystery_data?.playerCount}
                        initialScriptType={conversationData?.mystery_data?.scriptType as 'full' | 'pointForm'}
                        initialAdditionalDetails={conversationData?.mystery_data?.additionalDetails}
                        savedMysteryId={id}
                        onSave={handleSaveMessage}
                        initialMessages={messages}
                        isLoadingHistory={false}
                        systemInstruction={conversationData?.system_instruction}
                        skipForm={true}
                        needsInitialAIResponse={isInitial}
                        usePageScroll={true} // New prop to enable page-level scrolling
                    />
                </div>
            </main>

            {/* Fixed Bottom Action Button */}
            <div className={cn(
                "fixed bottom-20 left-0 right-0 z-10 px-4 py-2 bg-[#F7F3E9] shadow-none border-t-0",
                isMobile ? "px-3" : "px-4"
            )}>
                <div className={cn(
                    "mx-auto flex justify-center",
                    isMobile ? "max-w-full" : "max-w-4xl"
                )}>
                    <Button
                        onClick={handleGenerateFullMystery}
                        disabled={!hasAIResponse}
                        size={isMobile ? "default" : "lg"}
                        className={cn(
                            "bg-[#8B1538] hover:bg-[#6B0F28] text-white font-medium shadow-sm rounded-xl",
                            isMobile ? "w-full h-12 text-base" : "px-6"
                        )}
                    >
                        <Zap className="h-4 w-4 mr-2" />
                        Generate Full Mystery
                    </Button>
                </div>
            </div>
        </div>
    );
};

export default MysteryChatPage;
