name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - name: Delete all lock files and node_modules
        run: |
          rm -rf node_modules
          rm -f pnpm-lock.yaml
          rm -f yarn.lock
          rm -f package-lock.json
          rm -f .pnpmfile.cjs
          rm -f .pnp.*

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies with npm
        run: npm install
        
      - name: Build project
        run: |
          echo "=== Build Environment ==="
          node --version
          npm --version
          echo "=== Package.json build script ==="
          npm run build --verbose
          echo "=== Build completed, checking output ==="
          ls -la dist/
          echo "=== Verifying index.html exists ==="
          if [ -f dist/index.html ]; then
            echo "✓ index.html found"
            wc -l dist/index.html
          else
            echo "✗ index.html missing"
          fi

      - name: Create SPA 404.html
        run: |
          mkdir -p dist
          cat > dist/404.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <script>
                sessionStorage.redirect = location.href;
              </script>
              <meta http-equiv="refresh" content="0;URL='/'" />
            </head>
            <body></body>
          </html>
          EOF

      - name: Copy index.html to 404.html
        run: |
          if [ -f dist/index.html ]; then
            cp dist/index.html dist/404.html
          else
            echo "dist/index.html not found, build may have failed"
            ls -la dist/
            exit 1
          fi

      - name: Update index.html for SPA routing
        run: |
          sed -i '/<head>/a \
          <script>\
            (function(){\
              const redirect = sessionStorage.redirect;\
              delete sessionStorage.redirect;\
              if (redirect && redirect !== location.href) {\
                history.replaceState(null, null, redirect);\
              }\
            })();\
          </script>' dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
