name: Update Browserslist DB

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: npm ci

      - name: Update browserslist database
        run: |
          # Force use of npm instead of bun
          export BROWSERSLIST_DISABLE_CACHE=1
          export BROWSERSLIST_DONT_USE_BUN=1
          
          # Debug output
          echo "Using Node.js $(node -v)"
          echo "Using npm $(npm -v)"
          
          # Update browserslist using npm
          npx update-browserslist-db@latest --no-install
          
          echo "Browserslist database updated successfully"

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in browserslist database"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update browserslist database"
          file_pattern: "."

      - name: Summary
        run: |
          if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
            echo "✅ Browserslist database updated and committed"
          else
            echo "ℹ️ Browserslist database was already up to date"
          fi
