Run # Force npm usage by setting NPM environment variable
/bin/sh: 1: pnpm: not found
/home/runner/work/website-murder-mystery-party-generator/website-murder-mystery-party-generator/node_modules/update-browserslist-db/cli.js:39
      throw e
      ^

Error: Command failed: pnpm info caniuse-lite --json
/bin/sh: 1: pnpm: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at getLatestInfo (/home/runner/work/website-murder-mystery-party-generator/website-murder-mystery-party-generator/node_modules/update-browserslist-db/index.js:79:23)
    at updateDB (/home/runner/work/website-murder-mystery-party-generator/website-murder-mystery-party-generator/node_modules/update-browserslist-db/index.js:282:16)
    at Object.<anonymous> (/home/runner/work/website-murder-mystery-party-generator/website-murder-mystery-party-generator/node_modules/update-browserslist-db/cli.js:34:5)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32) {
  status: 127,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(28) [Uint8Array] [
       47,  98, 105, 110,  47, 115, 104,
       58,  32,  49,  58,  32, 112, 110,
      112, 109,  58,  32, 110, 111, 116,
       32, 102, 111, 117, 110, 100,  10
    ]
  ],
  pid: 2082,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(28) [Uint8Array] [
     47,  98, 105, 110,  47, 115, 104,
     58,  32,  49,  58,  32, 112, 110,
    112, 109,  58,  32, 110, 111, 116,
     32, 102, 111, 117, 110, 100,  10
  ]
}

Node.js v20.19.2
Error: Process completed with exit code 1.
